### PR TITLE
Update for Rails >= 5.1.4

### PR DESCRIPTION
**Pull request by cundd**
Fix basic installation in Redmine v4.x (#31)

### CODE REVIEW

**Comment by cundd** [comment]
Unfortunately it only "fixes" the upgrade/installation of Redmine with the Plugin installed. But it does not seem to actually make the plugin compatible with Redmine 4.x :(

**Comment by majkinetor** [comment]
There is one commit in network claiming 4.x
https://github.com/tkark/redmine_mattermost/commit/c19ac8754f4a15950e7dd1f22c254cf0fb86596f

**Comment by cundd** [comment]
Thank you for the hint.

I moved to https://github.com/AlphaNodes/redmine_messenger which worked quite well for me so far.

**Comment by thanosk** [comment]
Please try v0.6 and report back if it does not solve the issue.

**Pull request closed without merging**
